from pydantic import BaseModel, Field
from typing import List, Optional



class PracticeProblemOutput(BaseModel):
    """Represents a single practice problem generated by the AI."""
    problem_title: str = Field(description="A short, descriptive title for the problem.")
    problem_description: str = Field(description="A clear and concise description of the task or problem to solve.")
    hint: Optional[str] = Field(None, description="An optional hint to help the user solve the problem.")

class ProblemGenerationParams(BaseModel):
    """Input parameters for the practice problem generation agent."""
    topic_name: str
    subtopic_name: str
    source_text: str = Field(description="The full text context for the given subtopic.")